# Generated by Django 4.2.5 on 2023-09-06 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "slug",
                    models.SlugField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("description", models.TextField()),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("thumnail", models.ImageField(upload_to="")),
            ],
        ),
    ]
