# Generated by Django 4.2.5 on 2023-09-12 12:25

import apps.projects.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_thumnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="thumnail",
        ),
        migrations.AddField(
            model_name="project",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.projects.models.project_thumbnail_directory,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
