# Generated by Django 4.2.5 on 2023-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_project_thumnail_project_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
